### ISSUE TITLE
Update Client packages

### ISSUE THREAD

**Issue by NomanGul** [nielsenjared/mern#1]
Can you plz update the package.json of the client?

**Comment by nielsenjared** [comment]
Done https://github.com/nielsenjared/mern/commit/87c9c8db7991185b7f363b77b604eed38d111ef8

Thanks for the nudge. Are you using this? How did you find it?

**Comment by NomanGul** [comment]
Hi @nielsenjared Yes I'm using this because It's so simple. I'm an open source enthusiast and trying to explore unknown and super libraries/repos. I found yours and I just love it :heart:
